# Generated by Django 5.0.4 on 2024-05-04 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classID', models.BigAutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=128)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professorID', models.BigAutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=32)),
                ('firstName', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=32)),
                ('firstName', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('dayID', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='professorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professor'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleID', models.BigAutoField(primary_key=True, serialize=False)),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.class')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingID', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.class')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
