# Generated by Django 5.0.4 on 2024-05-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_rating_created_at_alter_class_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='professorCode',
            field=models.IntegerField(default=0),
        ),
    ]
