# Generated by Django 5.0.4 on 2024-05-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_professor_professorcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='division',
            field=models.CharField(default='Unassigned', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='program',
            field=models.CharField(default='Unassigned', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='schoolYear',
            field=models.CharField(default='Unassigned', max_length=128),
            preserve_default=False,
        ),
    ]
