# Generated by Django 5.0.4 on 2024-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_class_classid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='days',
            name='dayID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
