# Generated by Django 5.0.4 on 2024-05-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_class_classid_alter_days_dayid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratingID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='scheduleID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
