# Generated by Django 5.0.4 on 2024-05-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_rating_ratingid_alter_schedule_scheduleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rating1',
        ),
        migrations.AddField(
            model_name='rating',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating2',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rating3',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3),
            preserve_default=False,
        ),
    ]
