# Generated by Django 5.0.4 on 2024-05-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_rating_rating_rating1_rating_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating4',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3),
            preserve_default=False,
        ),
    ]
